### ISSUE TITLE
Make failed on MacOS

### ISSUE THREAD

**Issue by zhayujie** [smaeul/sun20i_d1_spl#13]
When I execute "make CROSS_COMPILE=riscv64-unknown-elf- p=sun20iw1p1 mmc", I get the following error:

sh /Users/zyj/zhayujie/sun20i_d1_spl/tools/generate_hash_header_file.sh > /Users/zyj/zhayujie/sun20i_d1_spl/include/commit_info.h.tmp
fatal: No names found, cannot describe anything.
if [ -r /Users/zyj/zhayujie/sun20i_d1_spl/include/commit_info.h ] && cmp -s /Users/zyj/zhayujie/sun20i_d1_spl/include/commit_info.h /Users/zyj/zhayujie/sun20i_d1_spl/include/commit_info.h.tmp; then rm -f /Users/zyj/zhayujie/sun20i_d1_spl/include/commit_info.h.tmp; else echo '  UPD     /Users/zyj/zhayujie/sun20i_d1_spl/include/commit_info.h'; mv /Users/zyj/zhayujie/sun20i_d1_spl/include/commit_info.h.tmp /Users/zyj/zhayujie/sun20i_d1_spl/include/commit_info.h; fi
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/zyj/zhayujie/sun20i_d1_spl/nboot mmc
  CHK     /Users/zyj/zhayujie/sun20i_d1_spl/include/config.h
  CHK     /Users/zyj/zhayujie/sun20i_d1_spl/autoconf.mk
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/zyj/zhayujie/sun20i_d1_spl/arch/riscv/cpu/riscv64/
/Users/zyj/zhayujie/sun20i_d1_spl/include/config.h: Assembler messages:
/Users/zyj/zhayujie/sun20i_d1_spl/include/config.h:4: 错误：junk at end of line, first unrecognized character is `-'
make[2]: *** [boot0_entry.o] Error 1
make[1]: *** [/Users/zyj/zhayujie/sun20i_d1_spl/arch/riscv/cpu/riscv64/libarch.o] Error 2
make: *** [mmc] Error 2

**Comment by smaeul** [comment]
How did you clone the repository? That error suggests you are missing the tags in the repository.
